baseURL = "https://ketansingh.me/"
languageCode = "en-us"
title = "Ketan Singh"
theme = "ezhil"
copyright = "© ketansingh.me"
pygmentsstyle = "solarized-light"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
disqusShortname = "ketansingh-me"

[params]
	mode = "dark"
	subtitle = "Collection of musing and ramblings"
	scheme = "light" # light, dark, gray or preference
	description = " library of musings and ramblings"
	featherIconsCDN = true
	googleAnalyticsID = "G-8HQBGC6R6T"


[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/spl0i7"

[[params.social]]
name = "Mail"
icon = "mail"
url = "mailto:a2V0YW5zaW5naC5zaEBnbWFpbC5jb20="



[taxonomies]
   tag = "tags"